END_PHRASE = [
    '? Eu ouvi críticas maravilhosas a respeito',
    ' e achei uma narrativa fascinante',
    ' Definitivamente, uma leitura obrigatória!',
    ' uma história que realmente me emocionou',
    ' É um título que tem gerado muita discusão',
    ' e gostaria de conhecer sua opinião',
    ' uma obra-prima da literatura contemporânea',
    ' e acho que seria perfeito para nossa próxima leitura do clube do livro',
    ' Recomendo fortemente para quem ama este gênero',
    ' especialmente pela abordagem única do autor',
    ' que oferece uma perspectiva muito interessante',
    ' É algo que planejo reler em breve',
    ' e estou ansioso para discutir isso em nosso próximo encontro',
    ' Já está na minha lista de favoritos',
    ' e gostaria de saber se vale a pena a leitura',
    '. Alguém está interessado em um debate sobre isso?',
    ', que foi recentemente adaptado para um filme',
    ' e acho que captura perfeitamente a essência do tópico',
    '. A maneira como os temas são explorados é incrível',
    '. Estou surpreso que não seja mais popular',
    ', uma saga que redefine os limites da ficção',
    ' e sua habilidade de entrelaçar destinos',
    ', onde cada página ferve com novas emoções',
    ', marcando um antes e um depois na literatura moderna',
    ', um título que desafia as expectativas',
    ' e sua viagem emocionante através de culturas',
    ', que está redefinindo a maneira como vemos a literatura',
    ' que desafia os limites do possível',
    ' Uma verdadeira obra de arte literária!',
    ' lançando nova luz sobre velhas tradições',
    '. É um daqueles livros que transforma o leitor',
    ' trazendo histórias marginalizadas para a frente e o centro',
    ' um ícone indiscutível da literatura rebelde',
    ' e sua inesgotável capacidade de surpreender e emocionar',
    ' revelando verdades universais através do particular',
    ' Sua riqueza de personagens é simplesmente fascinante',
    ', que consegue espelhar a alma humana como nenhum outro',
    ' Cada palavra é uma pincelada de mestre',
    ' um farol de esperança em tempos turbulentos.',
    ' A história ressoa muito tempo após a última página ser virada',
    ' uma ponte entre o passado esquecido e o presente vivido',
    ' Jamais a jornada interior foi tão vividamente retratada',
    ' uma balada épica tecida em realidade e fantasia',
    ' ',
    ' onde o fim é apenas o começo de uma reflexão profunda',
    ' Seu impacto cultural não pode ser subestimado',
    ' mostrando que as palavras são, de fato, mais afiadas que espadas',
    ' Uma tapeçaria ricamente imaginada de ideias e emoções',
    ' celebrando a diversidade da experiência humana',
    ' Este livro irá transportá-lo para mundos desconhecidos',
    ' provocando uma introspecção profunda e duradoura',
    ' A narrativa destemidamente aborda questões polêmicas',
    ' um oásis de imaginação e sabedoria em um mundo acelerado',
    '  eloquência do autor brilha intensamente em cada capítulo',
    ' conquistando corações e mentes de leitores ao redor do mundo',
    ' um lembrete de que a literatura é um espelho da sociedade',
    ' O livro irrompe com a força de um clássico instantâneo',
    ' ecoando as complexidades da vida real através da ficção',
    ' Prepare-se para questionar tudo o que você sabia sobre o gênero',
    ' A delicadeza com que trata temas difíceis é admirável',
    ' um tour de force literário que ressoa com autenticidade',
    ' Não é apenas uma história, mas uma exploração da condição humana',
    ' unindo leitores em sua jornada emocional compartilhada',
    ' A autenticidade das experiências retratadas é inegável',
    ', que nos inspira a olhar além de nossas próprias vidas',
    ' demonstrando a duradoura resiliência do espírito humano',
    ' uma história que você viverá mil vezes em sua mente',
    ' desafiando-nos a confrontar nossos próprios medos e desejos',
    ' Uma leitura indispensável para os buscadores de verdades ocultas',
    ' iluminando as sombras do coração humano com cada virar de página',
    ', desenrolando o tecido da realidade, fio por fio',
    ', um portal para as inúmeras faces do amor',
    ' onde o herói interior encontra sua verdadeira casa',
    ' Uma odisseia que é um espelho para a alma',
    ' iluminando os recantos mais escuros da psique humana',
    ' uma colisão de sonhos e dura realidade',
    ' Ecoa a eterna luta entre o bem e o mal',
    ' onde cada personagem respira vida nas páginas',
    ' Aqui jaz uma encruzilhada de paixões proibidas',
    ' entrelaçando destinos através de palavras magistrais',
    ' A jornada faz com que cada leitor seja um peregrino',
    ' solidificando seu lugar no panteão dos clássicos',
    ' tocando corações com a delicadeza de uma brisa',
    ' uma sinfonia escrita na linguagem das emoções',
    ' desafiando os leitores a uma jornada interior',
    ' mapeando as estrelas do firmamento humano',
    ' onde verdades universais são reveladas em sussurros',
    ' Neste livro, a esperança aprende a dançar com o medo',
    ' esculpindo memorias em prantos e risos',
    ' Uma saga onde cada fim é um novo começo',
    ' e no seu cerne, a fragilidade e força do espírito',
    ' Aqui, o impossível é apenas outro começo',
    ', abraçando o leitor em um mundo sem fronteiras',
    ', uma oferta de paz em tempos de turbulência',
    ', navegando pelos mares tempestuosos da mudança',
    ' No seu epílogo, um prelúdio para futuras jornadas',
    ' entoando um hino para a humanidade perdida e encontrada',
    ' e no seu final, a promessa da aurora eterna',
    ' pintando o crepúsculo com as cores do renascimento',
    ' Na sua melodia, os ecos do infinito',
    ', uma tapeçaria tecida com os fios da aventura e esperança',
    '. Sob suas asas, sonhos ousam voar',
    ', plantando sementes de rebelião nos jardins do conformismo',
    ', onde cada palavra é um eco do silêncio interior',
    '. Entre seus capítulos, segredos que o tempo esqueceu',
    ' refletindo a luz e trevas que residem em nós',
    ' servindo como bússola para almas perdidas',
    ' revelando que cada fim carrega o sussurro de um novo início',
    ' um manifesto do poder indomável do espírito humano',
    ' entrelaçando a melancolia e alegria com maestria',
    ' e nas suas linhas, a poesia da existência',
    ' um santuário onde até os corações quebrados encontram paz',
    ' e no seu rastro, o perfume de mundos esquecidos',
    ' onde cada sentença é uma prece atemporal',
    ' oferecendo um refúgio do caos em sua serenidade',
    ' uma promessa de liberdade sussurrada ao coração',
    '. Neste mundo, as sombras dançam com a luz',
    ', onde a redenção espera em um palco de papel',
    ' deixando uma cicatriz de luz na escuridão',
    ' ',
    ' um legado eterno no reino da palavra escrita',
    ' e em suas páginas, o abraço acolhedor do entender',
    ', onde cada capítulo desafia as fronteiras da imaginação',
    ' tecendo uma narrativa que dança na linha entre fantasia e realidade',
    ' e no final, um eco de eternidade que ressoa no silêncio',
    ', servindo como um espelho para os desejos e medos humanos',
    ' onde os murmúrios do passado encontram o presente em uma serenata eterna',
    ' unindo leitores em uma jornada compartilhada de descoberta e admiração',
    ' e em suas últimas palavras, uma quietude que fala mais do que palavras podem expressar',
    ', uma fortaleza para os espíritos que buscam refúgio na tempestade',
    ', e nas entrelinhas, mensagens esculpidas para a alma',
    ' uma odisseia que marca cada leitor com sua intensidade ardente',
    ' uma declaração de resistência contra as marés do esquecimento',
    ' onde a sabedoria floresce nas páginas como um jardim esquecido',
    ' marcando o caminho para territórios inexplorados do coração humano',
    ' um testamento para a resiliência do espírito humano',
    ' e nas margens de sua narrativa, ecos de imortalidade',
    ' onde a aventura e introspecção se entrelaçam em uma dança etérea',
    ' com personagens que habitam o coração muito tempo após a leitura',
    ' um farol de esperança em um mar de incertezas',
    ' concluindo com uma nota que ressoa no infinito de nossos próprios questionamentos',
    ' e na quietude de seu encerramento, a promessa de aventuras ainda não escritas',
    ' deixando o leitor com um sussurro de algo transcendente, à espera de ser descoberto',
    ' '
]