INITIAL_PHRASE = [
    'procure por titulo ',
    'procure por título ',
    'procure por nome ',
    'procure por obra ',
    'procure um livro por titulo ',
    'procure um livro por título ',
    'procure um livro por nome ',
    'pesquisar um livro por titulo ',
    'pesquisar um livro por título ',
    'pesquisar um livro por nome ',
    'buscar por titulo ',
    'buscar por nome ',
    '',
    'pesquise uma obra por titulo ',
    'pesquise uma obra por nome ',
    'liste livros por titulo ',
    'liste obras por nome ',
    'nome da obra ',
    'nome de obra ',
    'titulo ',
    'título ',
    'livro ',
    'obra ',
    'Você já leu o livro ',
    'Eu recomendaria a leitura de ',
    'Uma obra que me impactou foi ',
    'Não consigo parar de pensar em ',
    'Você poderia encontrar o livro ',
    'Eu gostaria de discutir sobre ',
    'Você tem algum comentário sobre ',
    'O que você acha de ',
    'Alguém já ouviu falar de ',
    'Estou pensando em comprar ',
    'Eles mencionaram o livro ',
    'Será que você poderia analisar ',
    'O autor destacou-se com a obra ',
    'A biblioteca tem uma cópia de ',
    'Você pode fazer o download de ',
    'Recentemente, tenho explorado ',
    'Fui profundamente influenciado por ',
    'Você pode facilmente se identificar com ',
    'Estou atualmente lendo ',
    'Você já teve a chance de olhar para ',
    'Será que vale a pena investir tempo em ',
    'Estou curioso sobre ',
    'Me deparei com uma crítica sobre ',
    'Na lista dos mais vendidos, temos ',
    'Um clássico que nunca envelhece: ',
    'Uma jornada literária começa com ',
    'Para uma mudança de perspectiva, tente ',
    'A narrativa cativante de ',
    'No clube do livro, estamos explorando ',
    'Conhecido por sua escrita profunda, o autor nos traz ',
    'Entre os pioneiros do gênero, destaca-se ',
    'Uma contribuição significativa à literatura: ',
    'Na minha estante de favoritos está ',
    'O crítico literário recomendou ',
    'Em uma entrevista, o autor mencionou ',
    'Vencedor de vários prêmios, ',
    'Na lista de finalistas do prêmio, encontramos ',
    'A próxima joia literária é ',
    'Navegando pela seção de best-sellers, encontrei ',
    'Revolucionando a literatura moderna, temos ',
    'No coração de cada leitor, há um espaço para ',
    'Nenhuma biblioteca está completa sem ',
    'Mergulhe no suspense de ',
    'Descubra a magia contida em ',
    'Rompendo barreiras literárias, apresentamos ',
    'Na intersecção da ficção e realidade: ',
    'Ecoando através de gerações, descubra ',
    'Um tesouro escondido no mundo literário: ',
    'Para corações aventureiros, recomendamos ',
    'Capturando a complexidade humana em ',
    'Desafiando as convenções com ',
    'Reimaginando um gênero, leia ',
    'Poucos livros conseguem emocionar como ',
    'Redescubra a história clássica de ',
    'Em um mundo próprio, explore ',
    'Provocando debates em todo o mundo, temos ',
    'Consolidando um lugar na história literária: ',
    'Redefinindo a experiência de leitura com ',
    'Poucos autores capturam a imaginação como o criador de ',
    'No topo da lista de leituras obrigatórias, está ',
    'A crítica literária está elogiando ',
    'Um fenômeno global indescritível: ',
    'Renovando o interesse pelo gênero, destacamos ',
    'Um relato autobiográfico poderoso: ',
    'Dando voz a histórias não contadas, apresentamos ',
    'Na vanguarda da literatura contemporânea, encontra-se ',
    'Elevando a narrativa a um novo patamar, ',
    'Com uma prosa inesquecível, somos levados a ',
    'Desenterrando mitos antigos em ',
    'Revelando a beleza escondida na literatura, temos ',
    'Transcendendo as fronteiras do tempo e espaço, ',
    'Um conto de fadas moderno conhecido como ',
    'Mudando completamente meu entendimento de arte, ',
    'Na encruzilhada entre realidade e fantasia, encontramos ',
    'Para os amantes do suspense, recomendo ',
    'Ressuscitando lendas esquecidas, o autor apresenta ',
    'Um labirinto de intrigas e reviravoltas chamado ',
    'Evocando nostalgia e novas aventuras, ',
    'Se perca nas profundezas enigmáticas de ',
    'Uma análise literária seria incompleta sem ',
    'Navegando pelas complexidades da mente humana, ',
    'Para aqueles que buscam conforto em palavras, ',
    'Um banquete para a mente e a alma, ',
    'Trazendo o passado à vida vívida, ',
    'Uma exploração poética do ser encontra-se em ',
    'A chave para mundos ocultos reside em ',
    'Desvendando os mistérios do universo através de ',
    'Um farol de sabedoria em meio à confusão, ',
    'Para uma aventura épica, não procure além de ',
    'Guiando os leitores através de maravilhas e horrores, ',
    'Testemunhe uma revolução no pensamento com ',
    'Acalmando a tempestade dentro de nossos corações, ',
    'Desvende segredos antigos lendo ',
    'Reimaginando o futuro com a distopia apresentada em ',
    'Acolhendo sonhadores e realistas, temos ',
    'Nas sombras do cotidiano, descobrimos ',
    ' ',
    'Um convite para questionar a realidade com ',
    'Libertando a imaginação cativa, apresento ',
    'Na busca por redenção, muitos encontram ',
    'Pintando a vida com palavras em ',
    'Desafiando a morte e o destino em ',
    'Entre as memórias esquecidas, revive ',
    'Numa sinfonia de prosa, destaca-se ',
    'Reescrevendo as regras da ficção, ',
    'Em homenagem às vozes silenciadas, lemos ',
    'Num campo de batalha literário, sobressai ',
    'Curando feridas invisíveis, o autor oferece ',
    'Em um coro de vozes literárias, uma se destaca: ',
    'Resgatando a esperança das cinzas, ',
    'Dentro de páginas manchadas de lágrimas, encontramos ',
    'Celebrando a eternidade do agora em ',
    'Na tessitura de realidades alternativas, está ',
    'Questionando a própria essência da existência, ',
    'Um remédio para a alma solitária no livro ',
    'Em uma ode ao espírito indomável, descobrimos ',
    'Caminhando pelos corredores sombrios da mente, você encontra ',
    'No palco da vida, o papel principal é de ',
    'Revivendo a inocência perdida, recomendo ',
    'Sob o céu estrelado da literatura brilha ',
    ' '
]