INITIAL_PHRASE = [
    'procure por titulo ',
    'procure por título ',
    'procure por nome ',
    'procure por obra ',
    'procure um livro por titulo ',
    'procure um livro por título ',
    'procure um livro por nome ',
    'pesquisar um livro por titulo ',
    'pesquisar um livro por título ',
    'pesquisar um livro por nome ',
    'buscar por titulo ',
    'buscar por nome ',
    '',
    'pesquise uma obra por titulo ',
    'pesquise uma obra por nome ',
    'liste livros por titulo ',
    'liste obras por nome ',
    'nome da obra ',
    'nome de obra ',
    'titulo ',
    'título ',
    'livro ',
    'obra ',
    'Você já leu o livro ',
    '',
    '',
    '',
    '',
    '',
    '',
    ' ',
    '',
    '',
    '',
    ' ',
    '',
    '',
    '',
    '',
    '',
    ' ',
    '',
    '',
    'Rompendo barreiras literárias, apresentamos ',
    'Na intersecção da ficção e realidade: ',
    'Ecoando através de gerações, descubra ',
    'Um tesouro escondido no mundo literário: ',
    'Para corações aventureiros, recomendamos ',
    'Capturando a complexidade humana em ',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Redefinindo a experiência de leitura com ',
    'Poucos autores capturam a imaginação como o criador de ',
    'No topo da lista de leituras obrigatórias, está ',
    'A crítica literária está elogiando ',
    '',
    ''
]